# Generated by Django 2.2 on 2022-03-04 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryDetectorServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.IntegerField()),
                ('date', models.DateField()),
                ('multi_user', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=300)),
                ('user_phone', models.BigIntegerField()),
                ('box_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeliveryDetectorServer.BoxInfo')),
            ],
        ),
        migrations.DeleteModel(
            name='UserAccountDummy',
        ),
    ]
