# Generated by Django 3.0.2 on 2022-03-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryDetectorServer', '0002_auto_20220304_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_pw',
            field=models.CharField(default='123', max_length=200),
            preserve_default=False,
        ),
    ]
