# Generated by Django 3.0.2 on 2022-02-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloworldmodel',
            name='model_info',
            field=models.CharField(default='tbd', max_length=300),
            preserve_default=False,
        ),
    ]
